import { useState } from "react";
import { Link } from "wouter";
import { Building2, CheckCircle2, ClipboardList, Edit3, ShieldCheck, UserRound, Users, XCircle } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Footer, Header } from "@/components/VukaShell";

type Section = "companies" | "applications" | "users";
export default function AdminBusiness({ section = "companies" }: { section?: Section }) {
  const { isAuthenticated, user } = useAuth(); const enabled = isAuthenticated && user?.role === "admin"; const [tab, setTab] = useState<Section>(section); const utils = trpc.useUtils();
  const companies = trpc.academy.admin.companies.useQuery(undefined, { enabled }); const applications = trpc.academy.admin.applications.useQuery(undefined, { enabled: enabled && tab === "applications" }); const [role, setRole] = useState("all"); const users = trpc.academy.admin.users.useQuery({ role }, { enabled: enabled && tab === "users" });
  const setCompanyStatus = trpc.academy.admin.setCompanyStatus.useMutation({ onSuccess: () => { toast.success("Estado da empresa atualizado."); void companies.refetch(); } }); const updateCompany = trpc.academy.admin.updateCompany.useMutation({ onSuccess: () => { toast.success("Empresa atualizada."); void companies.refetch(); } }); const review = trpc.academy.admin.reviewApplication.useMutation({ onSuccess: () => { toast.success("Candidatura atualizada."); void applications.refetch(); void companies.refetch(); } }); const setActive = trpc.academy.admin.setUserActive.useMutation({ onSuccess: () => { toast.success("Estado do utilizador atualizado."); void users.refetch(); } });
  if (!isAuthenticated || user?.role !== "admin") return <><Header /><main className="container flex min-h-[60vh] items-center py-20"><div className="rounded-[24px] bg-[#102b47] p-8 text-white"><ShieldCheck className="text-[#b8e2d6]" /><h1 className="mt-6 text-3xl font-extrabold">Acesso administrativo restrito</h1><Link href="/" className="mt-7 inline-flex rounded-full bg-[#b8e2d6] px-5 py-3 text-sm font-extrabold text-[#0b4151]">Voltar ao início</Link></div></main><Footer /></>;
  return <><Header /><main className="bg-[#f0f5f2] pb-20"><div className="container py-10 md:py-16"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow text-[#4f8f80]">Administração B2B</p><h1 className="display mt-3 text-4xl font-extrabold text-[#142335] md:text-5xl">Empresas e pessoas.</h1><p className="mt-4 max-w-2xl text-[#6a7780]">Aprove candidaturas, acompanhe parceiros e mantenha os acessos sob controlo.</p></div><Link href="/admin" className="rounded-full border border-[#bfd0c9] px-4 py-3 text-sm font-extrabold text-[#0b4151]">Centro de comando</Link></div><div className="mt-9 flex flex-wrap gap-2 rounded-[20px] bg-white p-2">{([["companies", "Empresas", Building2], ["applications", "Candidaturas", ClipboardList], ["users", "Utilizadores", Users]] as const).map(([key, label, Icon]) => <button key={key} onClick={() => setTab(key)} className={`inline-flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-extrabold ${tab === key ? "bg-[#b8e2d6] text-[#0b4151]" : "text-[#78868d]"}`}><Icon size={16} />{label}</button>)}</div>{tab === "companies" && <Companies rows={companies.data ?? []} onStatus={(id, status) => setCompanyStatus.mutate({ id, status })} onUpdate={value => updateCompany.mutate(value)} />}{tab === "applications" && <Applications rows={applications.data ?? []} onReview={(id, status) => review.mutate({ id, status })} />}{tab === "users" && <UsersPanel rows={users.data ?? []} role={role} setRole={setRole} onToggle={(id, active) => setActive.mutate({ userId: id, active: !active })} />}</div></main><Footer /></>;
}
function Companies({ rows, onStatus, onUpdate }: { rows: any[]; onStatus: (id: number, status: "approved" | "rejected" | "suspended" | "under_review") => void; onUpdate: (value: any) => void }) {
  const [editing, setEditing] = useState<any>(null);
  return <section className="mt-7 space-y-3">{rows.length ? rows.map(row => <div key={row.id} className="rounded-[22px] border border-[#dce5e1] bg-white p-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><Building2 size={20} className="text-[#0b7767]" /><h2 className="text-lg font-extrabold text-[#142335]">{row.name}</h2><Status value={row.status} /></div><p className="mt-3 text-sm text-[#6a7780]">{row.contactName ?? row.owner?.name ?? "Sem responsável"} · {row.contactEmail ?? row.owner?.email ?? "Sem email"}</p><p className="mt-1 text-xs text-[#78868d]">{row.country ?? "—"} · {row.city ?? "—"} · {row.sector ?? "—"} · {row.collaborators} colaboradores · {row.assignedCourses} cursos atribuídos</p>{editing?.id === row.id && <CompanyEditor value={editing} setValue={setEditing} onCancel={() => setEditing(null)} onSave={() => { onUpdate({ id: editing.id, name: editing.name, contactName: editing.contactName ?? "", contactEmail: editing.contactEmail || undefined, phone: editing.phone ?? "", country: editing.country ?? "", city: editing.city ?? "", sector: editing.sector ?? "", employeeCount: Number(editing.employeeCount ?? 0) }); setEditing(null); }} />}</div><div className="flex flex-wrap gap-2"><button onClick={() => setEditing({ ...row })} className="inline-flex items-center gap-2 rounded-full border border-[#bfd0c9] px-3 py-2 text-xs font-extrabold text-[#0b4151]"><Edit3 size={14} /> Editar</button>{row.status !== "approved" && <button onClick={() => onStatus(row.id, "approved")} className="inline-flex items-center gap-2 rounded-full bg-[#e3f0ed] px-3 py-2 text-xs font-extrabold text-[#0b7767]"><CheckCircle2 size={14} /> Aprovar</button>}{row.status === "approved" && <button onClick={() => onStatus(row.id, "suspended")} className="inline-flex items-center gap-2 rounded-full bg-[#fbe9e6] px-3 py-2 text-xs font-extrabold text-[#b55743]"><XCircle size={14} /> Suspender</button>}{row.status === "suspended" && <button onClick={() => onStatus(row.id, "approved")} className="rounded-full border border-[#bfd0c9] px-3 py-2 text-xs font-extrabold text-[#0b4151]">Reativar</button>}</div></div></div>) : <Empty text="Ainda não existem empresas registadas." />}</section>;
}
function CompanyEditor({ value, setValue, onCancel, onSave }: { value: any; setValue: (value: any) => void; onCancel: () => void; onSave: () => void }) { return <div className="mt-4 grid gap-3 rounded-xl border border-[#b8e2d6] bg-[#f4fbf8] p-4 md:grid-cols-3"><input value={value.name ?? ""} onChange={e => setValue({ ...value, name: e.target.value })} placeholder="Nome da empresa" className="h-10 rounded-lg border border-[#dce5e1] px-3 text-sm" /><input value={value.contactName ?? ""} onChange={e => setValue({ ...value, contactName: e.target.value })} placeholder="Responsável" className="h-10 rounded-lg border border-[#dce5e1] px-3 text-sm" /><input value={value.contactEmail ?? ""} onChange={e => setValue({ ...value, contactEmail: e.target.value })} placeholder="Email" className="h-10 rounded-lg border border-[#dce5e1] px-3 text-sm" /><input value={value.phone ?? ""} onChange={e => setValue({ ...value, phone: e.target.value })} placeholder="Telefone" className="h-10 rounded-lg border border-[#dce5e1] px-3 text-sm" /><input value={value.country ?? ""} onChange={e => setValue({ ...value, country: e.target.value })} placeholder="País" className="h-10 rounded-lg border border-[#dce5e1] px-3 text-sm" /><input value={value.city ?? ""} onChange={e => setValue({ ...value, city: e.target.value })} placeholder="Cidade" className="h-10 rounded-lg border border-[#dce5e1] px-3 text-sm" /><input value={value.sector ?? ""} onChange={e => setValue({ ...value, sector: e.target.value })} placeholder="Setor" className="h-10 rounded-lg border border-[#dce5e1] px-3 text-sm" /><input value={value.employeeCount ?? 0} onChange={e => setValue({ ...value, employeeCount: e.target.value })} type="number" placeholder="Colaboradores" className="h-10 rounded-lg border border-[#dce5e1] px-3 text-sm" /><div className="flex gap-2"><button onClick={onSave} className="rounded-full bg-[#0b4151] px-4 py-2 text-xs font-extrabold text-white">Guardar</button><button onClick={onCancel} className="rounded-full border border-[#bfd0c9] px-4 py-2 text-xs font-extrabold text-[#0b4151]">Cancelar</button></div></div>; }
function Applications({ rows, onReview }: { rows: any[]; onReview: (id: number, status: "under_review" | "approved" | "rejected") => void }) { const [status, setStatus] = useState("all"); const filtered = status === "all" ? rows : rows.filter(row => row.status === status); return <section className="mt-7"><div className="flex flex-wrap gap-2"><select value={status} onChange={e => setStatus(e.target.value)} className="filter-input"><option value="all">Todos os estados</option><option value="pending">Pendentes</option><option value="under_review">Em análise</option><option value="approved">Aprovadas</option><option value="rejected">Rejeitadas</option></select></div><div className="mt-4 space-y-3">{filtered.length ? filtered.map(row => <div key={row.id} className="rounded-[22px] border border-[#dce5e1] bg-white p-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><div className="flex items-center gap-3"><h2 className="text-lg font-extrabold text-[#142335]">{row.companyName}</h2><Status value={row.status} /></div><p className="mt-2 text-sm text-[#6a7780]">{row.contactName} · {row.businessEmail} · {row.phone ?? "sem telefone"}</p><p className="mt-1 text-xs text-[#78868d]">{row.country ?? "—"} · {row.city ?? "—"} · {row.sector ?? "—"} · {new Date(row.createdAt).toLocaleDateString("pt-PT")}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => onReview(row.id, "under_review")} className="rounded-full border border-[#bfd0c9] px-3 py-2 text-xs font-extrabold text-[#0b4151]">Em análise</button><button onClick={() => onReview(row.id, "approved")} className="rounded-full bg-[#0b4151] px-3 py-2 text-xs font-extrabold text-white">Aprovar</button><button onClick={() => onReview(row.id, "rejected")} className="rounded-full bg-[#fbe9e6] px-3 py-2 text-xs font-extrabold text-[#b55743]">Rejeitar</button></div></div></div>) : <Empty text="Não existem candidaturas neste filtro." />}</div></section>; }
function UsersPanel({ rows, role, setRole, onToggle }: { rows: any[]; role: string; setRole: (v: string) => void; onToggle: (id: number, active: boolean) => void }) { return <section className="mt-7"><select value={role} onChange={e => setRole(e.target.value)} className="filter-input"><option value="all">Todos os utilizadores</option><option value="estudante">Estudantes</option><option value="formador">Formadores</option><option value="empresa">Empresas</option><option value="admin">Administradores</option></select><div className="mt-4 space-y-3">{rows.length ? rows.map(row => <div key={row.id} className="flex flex-col justify-between gap-4 rounded-[20px] border border-[#dce5e1] bg-white p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#e3f0ed] text-[#0b7767]"><UserRound size={18} /></span><div><p className="font-extrabold text-[#142335]">{row.name ?? "Sem nome"}</p><p className="mt-1 text-xs text-[#78868d]">{row.email ?? "sem email"} · {row.role} · {new Date(row.createdAt).toLocaleDateString("pt-PT")}</p></div></div><button onClick={() => onToggle(row.id, row.isActive)} className={`rounded-full px-3 py-2 text-xs font-extrabold ${row.isActive ? "bg-[#e3f0ed] text-[#0b7767]" : "bg-[#fbe9e6] text-[#b55743]"}`}>{row.isActive ? "Desativar" : "Ativar"}</button></div>) : <Empty text="Não existem utilizadores para este filtro." />}</div></section>; }
function Status({ value }: { value: string }) { return <span className="rounded-full bg-[#e3f0ed] px-3 py-1 text-[11px] font-extrabold uppercase text-[#0b7767]">{value}</span>; }
function Empty({ text }: { text: string }) { return <div className="rounded-[22px] border border-dashed border-[#bfd0c9] bg-white p-10 text-center text-sm text-[#78868d]">{text}</div>; }
