import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { BarChart3, BookOpen, Building2, CheckCircle2, Download, FileBadge, LayoutDashboard, Plus, ShieldCheck, Users, UserX } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Footer, Header } from "@/components/VukaShell";

const nav = [["/empresa", "Dashboard", LayoutDashboard], ["/empresa/colaboradores", "Colaboradores", Users], ["/empresa/cursos", "Cursos", BookOpen], ["/empresa/desempenho", "Desempenho", BarChart3], ["/empresa/relatorios", "Relatórios", Download], ["/empresa/certificados", "Certificados", FileBadge]] as const;

export default function CompanyArea() {
  const { isAuthenticated, user } = useAuth();
  const [location] = useLocation();
  const enabled = isAuthenticated && user?.role === "empresa";
  const dashboard = trpc.academy.company.dashboard.useQuery(undefined, { enabled });
  const members = trpc.academy.company.members.useQuery(undefined, { enabled });
  const courses = trpc.academy.company.courses.useQuery(undefined, { enabled });
  const performance = trpc.academy.company.performance.useQuery(undefined, { enabled: enabled && ["/empresa/desempenho", "/empresa/relatorios"].includes(location) });
  const certificates = trpc.academy.company.certificates.useQuery(undefined, { enabled: enabled && location === "/empresa/certificados" });
  const utils = trpc.useUtils();
  const [member, setMember] = useState({ name: "", email: "" });
  const [assignment, setAssignment] = useState({ courseId: "", userId: "", dueAt: "" });
  const addMember = trpc.academy.company.addMember.useMutation({ onSuccess: () => { toast.success("Colaborador adicionado."); setMember({ name: "", email: "" }); void members.refetch(); } });
  const assignCourse = trpc.academy.company.assignCourse.useMutation({ onSuccess: () => { toast.success("Curso atribuído."); setAssignment({ courseId: "", userId: "", dueAt: "" }); void utils.academy.company.performance.invalidate(); } });
  const setActive = trpc.academy.company.setMemberActive.useMutation({ onSuccess: () => { toast.success("Estado atualizado."); void members.refetch(); } });
  const accessDenied = !isAuthenticated || user?.role !== "empresa";
  if (accessDenied) return <><Header /><main className="container flex min-h-[60vh] items-center py-20"><div className="rounded-[24px] bg-[#102b47] p-8 text-white"><Building2 className="text-[#b8e2d6]" /><h1 className="mt-6 text-3xl font-extrabold">Área empresarial restrita</h1><p className="mt-4 max-w-md leading-7 text-[#c9dddd]">Entre com a conta da sua empresa para aceder aos dados da equipa.</p><Link href="/" className="mt-7 inline-flex rounded-full bg-[#b8e2d6] px-5 py-3 text-sm font-extrabold text-[#0b4151]">Voltar ao início</Link></div></main><Footer /></>;
  const data = dashboard.data?.totals ?? { collaborators: 0, activeCollaborators: 0, assignedCourses: 0, inProgress: 0, completed: 0, averageProgress: 0, averageScore: 0, certificates: 0 };
  const exportCsv = () => { const rows = performance.data?.rows ?? []; const csv = ["Colaborador,Curso,Estado,Progresso,Nota", ...rows.map(row => [row.person?.name ?? row.person?.email ?? "", row.course?.title ?? "", row.status, row.progress, row.score].map(value => `"${String(value ?? "").replace(/"/g, '""')}"`).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "relatorio-empresa.csv"; link.click(); URL.revokeObjectURL(url); };
  return <><Header /><main className="bg-[#f0f5f2] pb-20"><div className="container py-8 md:py-12"><div className="flex flex-col gap-6 lg:flex-row"><aside className="lg:w-60 lg:shrink-0"><div className="rounded-[24px] bg-[#102b47] p-5 text-white lg:sticky lg:top-24"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#b8e2d6] text-[#0b4151]"><Building2 size={20} /></span><div><p className="text-xs font-extrabold">VUKA B2B</p><p className="text-[11px] text-[#b8e2d6]">Área da empresa</p></div></div><p className="mt-5 text-sm font-bold text-[#d2e2e0]">{dashboard.data?.company?.name ?? "A sua organização"}</p><nav className="mt-6 space-y-1">{nav.map(([href, label, Icon]) => <Link key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${location === href ? "bg-[#b8e2d6] text-[#0b4151]" : "text-[#c9dddd] hover:bg-white/10"}`}><Icon size={16} />{label}</Link>)}</nav></div></aside><section className="min-w-0 flex-1"><p className="eyebrow text-[#4f8f80]">Gestão empresarial</p><h1 className="display mt-3 text-4xl font-extrabold text-[#142335] md:text-5xl">Formação que move a equipa.</h1><p className="mt-4 max-w-2xl text-[#6a7780]">Acompanhe pessoas, cursos e resultados num só espaço protegido.</p>{location === "/empresa" && <Dashboard totals={data} />}{location === "/empresa/colaboradores" && <Members members={members.data ?? []} member={member} setMember={setMember} onAdd={() => addMember.mutate(member)} onToggle={(id, active) => setActive.mutate({ userId: id, active: !active })} pending={addMember.isPending} />}{location === "/empresa/cursos" && <Courses courses={courses.data ?? []} members={members.data ?? []} assignment={assignment} setAssignment={setAssignment} onAssign={() => assignCourse.mutate({ courseId: Number(assignment.courseId), userId: Number(assignment.userId), dueAt: assignment.dueAt ? new Date(assignment.dueAt) : undefined })} />}{location === "/empresa/desempenho" && <Performance data={performance.data} />}{location === "/empresa/relatorios" && <Reports data={performance.data} onCsv={exportCsv} />}{location === "/empresa/certificados" && <Certificates rows={certificates.data ?? []} />}</section></div></div></main><Footer /></>;
}
function Dashboard({ totals }: { totals: any }) { const cards = [["Colaboradores", totals.collaborators, Users], ["Cursos atribuídos", totals.assignedCourses, BookOpen], ["Em andamento", totals.inProgress, BarChart3], ["Concluídos", totals.completed, CheckCircle2], ["Progresso médio", `${totals.averageProgress}%`, BarChart3], ["Certificados", totals.certificates, FileBadge]] as const; return <div className="mt-9 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label, value, Icon]) => <div key={label} className="rounded-[22px] border border-[#dce5e1] bg-white p-6"><Icon size={19} className="text-[#0b7767]" /><p className="mt-5 text-3xl font-extrabold text-[#142335]">{value}</p><p className="mt-1 text-sm text-[#78868d]">{label}</p></div>)}</div>; }
function Members({ members, member, setMember, onAdd, onToggle, pending }: { members: any[]; member: any; setMember: (v: any) => void; onAdd: () => void; onToggle: (id: number, active: boolean) => void; pending: boolean }) { return <div className="mt-9 space-y-5"><div className="rounded-[24px] border border-[#dce5e1] bg-white p-6"><h2 className="text-xl font-extrabold text-[#142335]">Adicionar colaborador</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={member.name} onChange={e => setMember({ ...member, name: e.target.value })} placeholder="Nome completo" className="h-11 rounded-xl border border-[#dce5e1] px-3 text-sm" /><input value={member.email} onChange={e => setMember({ ...member, email: e.target.value })} placeholder="Email profissional" type="email" className="h-11 rounded-xl border border-[#dce5e1] px-3 text-sm" /></div><button onClick={onAdd} disabled={pending || !member.name || !member.email} className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#0b4151] px-5 py-3 text-sm font-extrabold text-white disabled:opacity-50"><Plus size={16} /> Adicionar / convidar</button></div><div className="space-y-3">{members.length ? members.map(row => <div key={row.id} className="flex items-center justify-between rounded-[20px] border border-[#dce5e1] bg-white p-5"><div><p className="font-extrabold text-[#142335]">{row.name ?? "Sem nome"}</p><p className="mt-1 text-xs text-[#78868d]">{row.email} · {row.assignedCourses} cursos</p></div><button onClick={() => onToggle(row.id, row.isActive)} className="inline-flex items-center gap-2 rounded-full border border-[#bfd0c9] px-3 py-2 text-xs font-extrabold text-[#0b4151]">{row.isActive ? <><UserX size={14} /> Desativar</> : "Reativar"}</button></div>) : <Empty text="Ainda não existem colaboradores nesta empresa." />}</div></div>; }
function Courses({ courses, members, assignment, setAssignment, onAssign }: { courses: any[]; members: any[]; assignment: any; setAssignment: (v: any) => void; onAssign: () => void }) { return <div className="mt-9 space-y-5"><div className="rounded-[24px] border border-[#dce5e1] bg-white p-6"><h2 className="text-xl font-extrabold text-[#142335]">Atribuir curso a colaborador</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><select value={assignment.courseId} onChange={e => setAssignment({ ...assignment, courseId: e.target.value })} className="h-11 rounded-xl border border-[#dce5e1] px-3 text-sm"><option value="">Escolher curso</option>{courses.map(course => <option key={course.id} value={course.id}>{course.title}</option>)}</select><select value={assignment.userId} onChange={e => setAssignment({ ...assignment, userId: e.target.value })} className="h-11 rounded-xl border border-[#dce5e1] px-3 text-sm"><option value="">Escolher colaborador</option>{members.filter(row => row.isActive).map(member => <option key={member.id} value={member.id}>{member.name ?? member.email}</option>)}</select><input type="date" value={assignment.dueAt} onChange={e => setAssignment({ ...assignment, dueAt: e.target.value })} className="h-11 rounded-xl border border-[#dce5e1] px-3 text-sm" /></div><button onClick={onAssign} disabled={!assignment.courseId || !assignment.userId} className="mt-4 rounded-full bg-[#0b4151] px-5 py-3 text-sm font-extrabold text-white">Atribuir curso</button></div><div className="grid gap-3 md:grid-cols-2">{courses.length ? courses.map(course => <div key={course.id} className="rounded-[20px] border border-[#dce5e1] bg-white p-5"><BookOpen size={18} className="text-[#0b7767]" /><h3 className="mt-4 font-extrabold text-[#142335]">{course.title}</h3><p className="mt-2 text-sm text-[#78868d]">{course.description}</p></div>) : <Empty text="Não existem cursos empresariais publicados." />}</div></div>; }
function Performance({ data }: { data: any }) { return <div className="mt-9"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Atribuições" value={data?.totals.assignments ?? 0} /><Metric label="Concluídos" value={data?.totals.completed ?? 0} /><Metric label="Progresso médio" value={`${data?.totals.averageProgress ?? 0}%`} /></div><div className="mt-5 space-y-3">{(data?.rows ?? []).map((row: any) => <div key={row.id} className="rounded-[20px] border border-[#dce5e1] bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-extrabold text-[#142335]">{row.person?.name ?? row.person?.email}</p><p className="mt-1 text-sm text-[#78868d]">{row.course?.title}</p></div><span className="rounded-full bg-[#e3f0ed] px-3 py-2 text-xs font-extrabold text-[#0b7767]">{row.status} · {row.progress}%</span></div></div>)}</div></div>; }
function Reports({ data, onCsv }: { data: any; onCsv: () => void }) { return <div className="mt-9 rounded-[24px] border border-[#dce5e1] bg-white p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow text-[#4f8f80]">Relatórios empresariais</p><h2 className="mt-2 text-2xl font-extrabold text-[#142335]">Resultados da sua equipa</h2></div><div className="flex gap-2"><button onClick={onCsv} className="inline-flex items-center gap-2 rounded-full border border-[#bfd0c9] px-4 py-3 text-sm font-extrabold text-[#0b4151]"><Download size={15} /> CSV</button><a href="/api/reports/company.pdf" download className="inline-flex items-center gap-2 rounded-full bg-[#0b4151] px-4 py-3 text-sm font-extrabold text-white"><Download size={15} /> PDF</a></div></div><p className="mt-5 text-sm leading-7 text-[#6a7780]">O relatório respeita o isolamento da sua empresa e apresenta apenas atribuições, progresso e desempenho dos seus colaboradores.</p><Performance data={data} /></div>; }
function Certificates({ rows }: { rows: any[] }) { return <div className="mt-9 space-y-3">{rows.length ? rows.map(row => <div key={row.id} className="flex items-center justify-between rounded-[20px] border border-[#dce5e1] bg-white p-5"><div className="flex items-center gap-3"><FileBadge className="text-[#0b7767]" /><div><p className="font-extrabold text-[#142335]">{row.user?.name ?? row.user?.email}</p><p className="mt-1 text-sm text-[#78868d]">{row.course?.title} · {row.certificateNumber}</p></div></div><span className="text-xs font-bold text-[#78868d]">{new Date(row.issuedAt).toLocaleDateString("pt-PT")}</span></div>) : <Empty text="A sua empresa ainda não tem certificados obtidos." />}</div>; }
function Metric({ label, value }: { label: string; value: number | string }) { return <div className="rounded-[20px] border border-[#dce5e1] bg-white p-5"><p className="text-2xl font-extrabold text-[#142335]">{value}</p><p className="mt-1 text-xs text-[#78868d]">{label}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-[20px] border border-dashed border-[#bfd0c9] bg-white p-8 text-center text-sm text-[#78868d]">{text}</div>; }
