import { BarChart3, BookOpen, CheckCircle2, Clock3, Target, Users } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Footer, Header } from "@/components/VukaShell";

export default function InstructorReports() {
  const { isAuthenticated, user } = useAuth();
  const report = trpc.academy.formador.performance.useQuery(undefined, { enabled: isAuthenticated && (user?.role === "formador" || user?.role === "admin") });
  if (!isAuthenticated || !["formador", "admin"].includes(user?.role ?? "")) return <><Header /><main className="container flex min-h-[60vh] items-center py-20"><div className="rounded-[24px] bg-[#102b47] p-8 text-white"><BarChart3 className="text-[#b8e2d6]" /><h1 className="mt-5 text-3xl font-extrabold">Relatórios para formadores</h1><p className="mt-3 max-w-md text-[#c9dddd]">Entre com uma conta de formador para acompanhar os seus cursos.</p><Link href="/" className="mt-6 inline-flex rounded-full bg-[#b8e2d6] px-5 py-3 text-sm font-extrabold text-[#0b4151]">Voltar ao início</Link></div></main><Footer /></>;
  const totals = report.data?.totals ?? { students: 0, averageProgress: 0, completionRate: 0, averageQuizScore: 0, pendingAssignments: 0 };
  return <><Header /><main className="bg-[#f0f5f2] pb-20"><div className="container py-10 md:py-16"><p className="eyebrow text-[#4f8f80]">Área do formador</p><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="display mt-3 text-4xl font-extrabold text-[#142335] md:text-5xl">Os seus alunos estão a avançar.</h1><p className="mt-4 max-w-2xl text-base text-[#6a7780]">Use estes sinais para identificar conquistas, desbloqueios e onde uma intervenção pode criar mais impacto.</p></div><Link href="/admin/curriculum" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#0b4151] px-5 py-3 text-sm font-extrabold text-white">Gerir conteúdos</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric icon={Users} label="Alunos ativos" value={totals.students} /><Metric icon={BarChart3} label="Progresso médio" value={`${totals.averageProgress}%`} /><Metric icon={CheckCircle2} label="Conclusão" value={`${totals.completionRate}%`} /><Metric icon={Target} label="Quiz médio" value={`${totals.averageQuizScore}%`} /><Metric icon={Clock3} label="Trabalhos pendentes" value={totals.pendingAssignments} /></div><section className="mt-10"><div className="flex items-center justify-between"><div><p className="eyebrow text-[#4f8f80]">Desempenho por curso</p><h2 className="mt-2 text-2xl font-extrabold text-[#142335]">Onde concentrar atenção</h2></div><span className="text-sm text-[#78868d]">Atualizado agora</span></div><div className="mt-5 grid gap-4">{(report.data?.courses ?? []).length === 0 ? <div className="rounded-[24px] border border-dashed border-[#bfd0c9] bg-white p-10 text-center text-sm text-[#6a7780]">Ainda não tem cursos atribuídos.</div> : report.data?.courses.map(course => <div key={course.courseId} className="rounded-[24px] border border-[#dce5e1] bg-white p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-3"><BookOpen className="text-[#0b7767]" size={19} /><h3 className="text-lg font-extrabold text-[#142335]">{course.title}</h3></div><p className="mt-2 text-sm text-[#78868d]">{course.students} alunos · {course.pendingAssignments} trabalhos aguardam correção</p></div><span className="rounded-full bg-[#e3f0ed] px-3 py-2 text-xs font-extrabold text-[#0b7767]">{course.averageProgress}% progresso médio</span></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><Bar label="Progresso" value={course.averageProgress} color="bg-[#55b9a1]" /><Bar label="Conclusão" value={course.completionRate} color="bg-[#e2a04e]" /><Bar label="Quiz médio" value={course.averageQuizScore} color="bg-[#6d59c7]" /></div></div>)}</div></section></div></main><Footer /></>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: number | string }) { return <div className="rounded-[20px] border border-[#dce5e1] bg-white p-5"><Icon size={18} className="text-[#0b7767]" /><p className="mt-4 text-2xl font-extrabold text-[#142335]">{value}</p><p className="mt-1 text-xs font-semibold text-[#78868d]">{label}</p></div>; }
function Bar({ label, value, color }: { label: string; value: number; color: string }) { return <div><div className="flex justify-between text-xs font-extrabold text-[#51606b]"><span>{label}</span><span>{value}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#e8efec]"><div className={`h-full rounded-full ${color}`} style={{ width: `${Math.min(100, value)}%` }} /></div></div>; }
