import { Link } from "wouter";
import { ArrowLeft, CreditCard, FileText, ReceiptText } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Footer, Header } from "@/components/VukaShell";

const labels: Record<string, string> = { pending: "Pendente", processing: "Em processamento", paid: "Pago", failed: "Recusado", cancelled: "Cancelado", refunded: "Reembolsado" };
export default function PaymentHistory() {
  const { isAuthenticated, user } = useAuth();
  const query = trpc.academy.student.payments.useQuery(undefined, { enabled: isAuthenticated });
  if (!isAuthenticated) return <><Header /><main className="container py-24 text-center"><h1 className="text-3xl font-extrabold text-[#142335]">Entre para ver os seus pagamentos.</h1><Link href="/" className="mt-6 inline-flex rounded-full bg-[#0b4151] px-5 py-3 text-sm font-extrabold text-white">Voltar ao início</Link></main><Footer /></>;
  return <><Header /><main className="bg-[#f0f5f2] pb-20"><div className="container py-10 md:py-16"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-bold text-[#0b7767]"><ArrowLeft size={15} /> Área do estudante</Link><div className="mt-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow text-[#4f8f80]">Conta de {user?.name?.split(" ")[0] ?? "estudante"}</p><h1 className="display mt-3 text-4xl font-extrabold text-[#142335] md:text-5xl">Histórico de pagamentos.</h1><p className="mt-4 text-[#6a7780]">Consulte compras, estados e referências de transação.</p></div><div className="rounded-full bg-[#e3f0ed] px-4 py-2 text-xs font-extrabold text-[#0b7767]"><CreditCard size={14} className="mr-2 inline" />{query.data?.length ?? 0} registos</div></div><div className="mt-9 space-y-3">{query.isLoading ? <div className="rounded-[22px] bg-white p-8 text-center text-sm text-[#6a7780]">A carregar histórico…</div> : query.data?.length ? query.data.map(payment => <div key={payment.id} className="rounded-[22px] border border-[#dce5e1] bg-white p-5 md:p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#e3f0ed] text-[#0b7767]"><ReceiptText size={19} /></span><div><h2 className="font-extrabold text-[#142335]">{payment.course.title}</h2><p className="mt-1 text-sm text-[#6a7780]">{new Date(payment.createdAt).toLocaleDateString("pt-PT")} · {payment.provider}</p><p className="mt-1 text-xs text-[#78868d]">Transação: {payment.transactionId ?? "aguarda confirmação"}</p></div></div><div className="flex items-center gap-4 md:text-right"><div><p className="font-extrabold text-[#142335]">{Number(payment.amount).toLocaleString("pt-MZ")} {payment.currency}</p><span className={`mt-1 inline-flex rounded-full px-3 py-1 text-[11px] font-extrabold ${payment.status === "paid" ? "bg-[#e3f0ed] text-[#0b7767]" : payment.status === "failed" ? "bg-[#fbe9e6] text-[#b55743]" : "bg-[#fff4d9] text-[#89652f]"}`}>{labels[payment.status] ?? payment.status}</span></div>{payment.receiptFileKey && <button className="grid h-9 w-9 place-items-center rounded-full bg-[#eef4f0] text-[#0b4151]" aria-label="Abrir recibo"><FileText size={16} /></button>}</div></div></div>) : <div className="rounded-[22px] border border-dashed border-[#bfd0c9] bg-white p-12 text-center"><CreditCard className="mx-auto text-[#0b7767]" /><h2 className="mt-4 font-extrabold text-[#142335]">Ainda não existem pagamentos.</h2><p className="mt-2 text-sm text-[#6a7780]">Quando comprar um curso, o histórico aparecerá aqui.</p><Link href="/cursos" className="mt-6 inline-flex rounded-full bg-[#0b4151] px-5 py-3 text-sm font-extrabold text-white">Explorar cursos</Link></div>}</div></div></main><Footer /></>;
}
