import { Link } from "wouter";
import { LayoutDashboard, LogIn, LogOut, Menu, Search, X } from "lucide-react";
import { useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";

const navItems = [["Cursos", "/cursos"], ["Categorias", "/categorias"], ["Instrutores", "/instrutores"], ["Para empresas", "/empresas"], ["Sobre nós", "/sobre-nos"]] as const;

export function Logo({ inverse = false }: { inverse?: boolean }) { return <Link href="/" className={`flex items-center gap-3 ${inverse ? "text-white" : "text-[#102b47]"}`}><span className={`grid h-9 w-9 place-items-center rounded-xl ${inverse ? "bg-[#b8e2d6] text-[#0b4151]" : "bg-[#0b4151] text-[#b8e2d6]"}`}><span className="text-lg font-extrabold leading-none">V</span></span><span className="leading-none"><span className="block text-[15px] font-extrabold tracking-[.12em]">VUKA</span><span className={`block pt-1 text-[9px] font-semibold tracking-[.24em] ${inverse ? "text-[#b8e2d6]" : "text-[#4f8f80]"}`}>ACADEMY</span></span></Link>; }

export function Header() {
  const [open, setOpen] = useState(false);
  const { user, isAuthenticated, logout } = useAuth();
  return <header className="sticky top-0 z-50 border-b border-[#dfe8e4]/80 bg-[#f7f8f5]/92 backdrop-blur-xl"><div className="container flex h-[76px] items-center justify-between gap-8"><Logo /><nav className="hidden items-center gap-7 lg:flex" aria-label="Navegação principal">{navItems.map(([label, href]) => <Link key={href} href={href} className="text-sm font-semibold text-[#51606b] transition-colors hover:text-[#0b4151]">{label}</Link>)}</nav><div className="hidden items-center gap-3 lg:flex"><Link href="/cursos" className="grid h-10 w-10 place-items-center rounded-full text-[#51606b] hover:bg-[#e8efec]" aria-label="Pesquisar cursos"><Search size={18} /></Link>{isAuthenticated ? <><Link href="/dashboard" className="flex items-center gap-2 rounded-full px-4 py-2 text-sm font-bold text-[#0b4151] hover:bg-[#e8efec]"><LayoutDashboard size={16} />{user?.name?.split(" ")[0] ?? "Área pessoal"}</Link><button onClick={() => logout()} className="grid h-10 w-10 place-items-center rounded-full text-[#51606b] hover:bg-[#e8efec]" aria-label="Sair"><LogOut size={16} /></button></> : <><button onClick={() => startLogin()} className="flex items-center gap-2 rounded-full px-4 py-2 text-sm font-bold text-[#0b4151] hover:bg-[#e8efec]"><LogIn size={16} />Entrar</button><button onClick={() => startLogin()} className="rounded-full bg-[#0b4151] px-5 py-3 text-sm font-bold text-white">Criar conta</button></>}</div><button className="grid h-10 w-10 place-items-center rounded-full bg-[#e8efec] text-[#0b4151] lg:hidden" onClick={() => setOpen(!open)} aria-label="Abrir menu">{open ? <X size={19} /> : <Menu size={19} />}</button></div>{open && <div className="border-t border-[#dfe8e4] bg-[#f7f8f5] px-6 py-5 lg:hidden"><div className="container flex flex-col gap-4">{navItems.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)} className="text-sm font-bold text-[#51606b]">{label}</Link>)}<button onClick={() => startLogin()} className="flex items-center justify-center gap-2 rounded-full bg-[#0b4151] px-4 py-3 text-sm font-bold text-white"><LogIn size={16} />Entrar</button></div></div>}</header>;
}

export function Footer() { return <footer className="bg-[#102b47] text-white"><div className="container grid gap-12 py-16 md:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><Logo inverse /><p className="mt-6 max-w-xs text-sm leading-7 text-[#c1d2d5]">Educação que abre caminhos, fortalece pessoas e prepara organizações para o futuro.</p></div><FooterColumn title="Plataforma" links={[["Cursos", "/cursos"], ["Categorias", "/categorias"], ["Certificados", "/dashboard/certificados"]]} /><FooterColumn title="Empresa" links={[["Sobre nós", "/sobre-nos"], ["Para empresas", "/empresas"], ["Contactos", "/contactos"]]} /><FooterColumn title="Suporte" links={[["Central de ajuda", "/ajuda"], ["FAQ", "/faq"], ["Privacidade", "/privacidade"]]} /></div><div className="border-t border-white/10"><div className="container py-5 text-xs text-[#9fb5ba]">© 2026 VUKA Academy. Todos os direitos reservados.</div></div></footer>; }
function FooterColumn({ title, links }: { title: string; links: readonly (readonly [string, string])[] }) { return <div><p className="eyebrow text-[#b8e2d6]">{title}</p><div className="mt-5 flex flex-col gap-3">{links.map(([label, href]) => <Link href={href} key={href} className="text-sm text-[#c1d2d5] transition hover:text-white">{label}</Link>)}</div></div>; }
